export const localData = [
  {
    id: 1,
    name: "Black Mamba - Gaming Chair",
    price: 1600,
    image:
      "https://i.pinimg.com/564x/ed/f4/3a/edf43a83b08af84d1d84e4ff48986eda.jpg",
    category: "Chairs",
    inCartQuantity: 1,
    stock: 17,
    desc: "Black gaming chair super comfortable. Perfect for gaming.",
    isNew: false,
  },
  {
    id: 2,
    name: "White Blade - Gaming Chair",
    price: 2100,
    image:
      "https://i.pinimg.com/564x/08/ca/94/08ca94c9dd9f518fade18aeffdaf87ea.jpg",
    category: "Chairs",
    inCartQuantity: 1,
    stock: 12,
    desc: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsumlorem ipsum lorem ipsum",
    isNew: false,
  },
  {
    id: 3,
    name: "Red Dragon - Gaming Chair",
    price: 2900,
    image:
      "https://i.pinimg.com/564x/f2/21/96/f22196ab5c77e4cf5dc74d571376962b.jpg",
    category: "Chairs",
    inCartQuantity: 1,
    stock: 9,
    desc: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsumlorem ipsum lorem ipsum",
    isNew: true,
  },
  {
    id: 4,
    name: "Blue Wizard - Gaming Chair",
    price: 2200,
    image:
      "https://i.pinimg.com/564x/50/95/16/50951664b71c408747ffe240325fdd19.jpg",
    category: "Chairs",
    inCartQuantity: 1,
    stock: 8,
    desc: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsumlorem ipsum lorem ipsum",
    isNew: true,
  },
  {
    id: 5,
    name: "Black Hole - Desk Pad",
    price: 105,
    image:
      "https://cdn.shopify.com/s/files/1/0277/5783/8449/products/product-image-1260143440_720x.jpg?v=1626846829",
    category: "Desk Pads",
    inCartQuantity: 1,
    stock: 26,
    desc: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsumlorem ipsum lorem ipsum",
    isNew: false,
  },
  {
    id: 6,
    name: "Inspiration - Desk Pad",
    price: 115,
    image:
      "https://cdn.shopify.com/s/files/1/0277/5783/8449/products/product-image-1464222697_720x.jpg?v=1631040068",
    category: "Desk Pads",
    inCartQuantity: 1,
    stock: 14,
    desc: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsumlorem ipsum lorem ipsum",
    isNew: true,
  },
  {
    id: 7,
    name: "Water tide - Desk Pad",
    price: 115,
    image:
      "https://cdn.shopify.com/s/files/1/0277/5783/8449/products/product-image-1695981967_720x.jpg?v=1631397944",
    category: "Desk Pads",
    inCartQuantity: 1,
    stock: 18,
    desc: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsumlorem ipsum lorem ipsum",
    isNew: false,
  },
  {
    id: 8,
    name: "Mind flow - Desk Pad",
    price: 110,
    image:
      "https://cdn.shopify.com/s/files/1/0277/5783/8449/products/product-image-1122899194_ff3fd928-31d9-4061-bdac-21c4bfdcf263_720x.jpg?v=1625773566",
    category: "Desk Pads",
    inCartQuantity: 1,
    stock: 6,
    desc: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsumlorem ipsum lorem ipsum",
    isNew: true,
  },
  {
    id: 9,
    name: "Basic - Desk",
    price: 400,
    image:
      "https://www.huzaro.pl/userdata/public/gfx/6431/hero_1.8_black_ackesoria.jpg",
    category: "Desk",
    inCartQuantity: 1,
    stock: 11,
    desc: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsumlorem ipsum lorem ipsum",
    isNew: false,
  },
  {
    id: 10,
    name: "Mega Black - Desk",
    price: 890,
    image: "https://www.huzaro.pl/userdata/public/gfx/1926/1111.jpg",
    category: "Desk",
    inCartQuantity: 1,
    stock: 8,
    desc: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsumlorem ipsum lorem ipsum",
    isNew: true,
  },
  {
    id: 11,
    name: "Mega White - Desk",
    price: 890,
    image:
      "https://www.huzaro.pl/userdata/public/gfx/9560dd11cf3d9dc5546c8bba43ce8d3f.jpg",
    category: "Desk",
    inCartQuantity: 1,
    stock: 8,
    desc: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsum lorem ipsumlorem ipsum lorem ipsum",
    isNew: false,
  },
];
