export const actionsCartTypes = {
  ADD_TO_CART: "ADD_TO_CART",
  DELETE_ITEM_FROM_CART: "DELETE_ITEM_FROM_CART",
  DELETE_WHOLE_FROM_CART: "DELETE_WHOLE_FROM_CART",
};

export const actionsProductsTypes = {
  FILTER_BY_CATEGORIES: "FILTER_BY_CATEGORIES",
  SEARCH_BY_PHRASE: "SEARCH_BY_PHRASE",

  FILTER_PRODUCTS: "FILTER_PRODUCTS",

  //handlers
  HANDLE_SEARCH_PRODUCT_INPUT: "HANDLE_SEARCH_PRODUCT_INPUT",
  HANDLE_CATEGORY_PRODUCT_CHANGE: "HANDLE_CATEGORY_PRODUCT_CHANGE",
  HANDLE_PRICE_RANGE_PRODUCT_INPUT: "HANDLE_PRICE_RANGE_PRODUCT_INPUT",
};

export const actionsUserTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
};
